#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE SAIL;
	GRANT ALL PRIVILEGES ON DATABASE SAIL TO "$POSTGRES_USER";
	\connect SAIL;
	CREATE SCHEMA SAIL0000V;
EOSQL
